" Absolute essentials
inoremap kj <Esc> 
colorscheme industry
let mapleader="\\"
set encoding=utf-8
set clipboard=unnamed
set ruler
set number
set fileformat=unix

filetype plugin indent on
syntax on

nnoremap <silent> <Tab> >>
nnoremap <silent> <S-Tab> <<

" Split navigations
set splitbelow
set splitright
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Enable folding with spacebar
set foldmethod=indent
set foldlevel=99
nnoremap <space> za

" Edit and source .vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Quote words
nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
nnoremap <leader>' viw<esc>a'<esc>bi'<esc>lel
nnoremap <leader>` viw<esc>a`<esc>bi`<esc>lel

" Wrap in brackets
nnoremap <leader>] 0i[<C-c>A]<C-c>
nnoremap <leader>) 0i(<C-c>A)<C-c>
nnoremap <leader>} 0i{<C-c>A}<C-c>

" Underline current line
nnoremap <leader>- yypv$r-<esc>

" Will make a better version of these...
:autocmd FileType javascript nnoremap <buffer> <localleader>c I//<esc>
:autocmd FileType python     nnoremap <buffer> <localleader>c I#<esc>

filetype plugin indent on    " required

iabbrev adn and
iabbrev dfe def

"defaults for indentation
set shiftwidth=2
set tabstop=2
set softtabstop=2

"no more flash!
set vb t_vb=

set smartindent
set autowrite
set bg=dark
set expandtab
set mouse=a
set nocompatible
set ofu=syntaxcomplete#Complete
set showmatch

" autosave when focus is lost
:au FocusLost * :wa


" Vundle setup - add plugins here.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'benmills/vimux'

call vundle#end()
