# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

source ~/.bashrc
bindkey -e

timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}

source ~/.zsh_prompt

# Overrides the existing function from fpath
# and autocompletes python -m [module]
# Assumes that "python" is defined!
_python_modules() {

  local modules

  # Technically this gets packages and not modules, BUT it generates
  # all of the packages in the current path. Which is usually what I want
  # to autocomplete.
  modules=(${(f)"$(python3 -c 'import pkgutil; print("\n".join(m.name for m in pkgutil.walk_packages(["."])))')"})

  # Use compadd to add the completions without a trailing space
  # -Q: Quotes the results to handle any special characters properly.
  # -S '': Ensures no trailing space is added after the completions.
  # --: Signals the end of options for compadd, 
  #     ensuring that all following arguments are treated 
  #     as completion suggestions.
  compadd -Q -S '' -- $modules
}
